name: R2 Backup

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed

jobs:
  r2-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: R2 Backup
        uses: ./
        env:
          ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
        with:
          args: --overwrite --remove
